app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /{_locale}

app_without_locale:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: homepage
        permanent: false

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# Redirect profile viewing to profile editing
fos_user_profile_show:
    path: /{_locale}/profile/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: fos_user_profile_edit
        permanent: true
