security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: fos_user_security_logout
            anonymous:    true

    access_control:
        - { path: '^/[a-z]{2}/login$', role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/[a-z]{2}/register', role: ROLE_ADMIN }
        - { path: '^/[a-z]{2}/resetting', role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/[a-z]{2}/members', role: IS_AUTHENTICATED_REMEMBERED }
        - { path: '^/admin', role: ROLE_ADMIN }
