# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.form.profile:
        class: UserBundle\Form\ProfileFormType
        tags:
            - { name: form.type, alias: app_user_profile }

    admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, UserBundle\Entity\User, ~]
        calls:
            - method: setUserManager
              arguments:
                  - '@fos_user.user_manager'
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Club List', label: User }
        public: true
